### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by sylphia-nox** [alllexx88/python-docx-split-run#1]
Hello!  I came across this code through your comment on an issue and would really like to use it in my project.  However, since it doesn't have a license, legally, I cannot integrate it into anything else.  Can you please add a license?

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license

https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

**Comment by alllexx88** [comment]
Done, glad this code is useful for you!
